# Generated by Django 2.1.1 on 2018-09-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20180923_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
