# Generated by Django 2.1.1 on 2018-10-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_item_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
    ]
