# Generated by Django 2.1.1 on 2018-09-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=2048, verbose_name='Description'),
        ),
    ]
