# Generated by Django 2.1.1 on 2018-10-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_item_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='pending',
        ),
    ]
