# Generated by Django 2.1.1 on 2018-10-24 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_item_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 19, 29), verbose_name='Deadline'),
            preserve_default=False,
        ),
    ]
