# Generated by Django 2.1.1 on 2018-10-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_auto_20181024_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('BN', 'Banned'), ('DU', 'Due'), ('AD', 'Adjucated')], default='AC', max_length=2),
        ),
    ]
