# Generated by Django 2.1.1 on 2018-10-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
    ]
